# Dev Container com base no Docker Compose
FROM mcr.microsoft.com/vscode/devcontainers/dotnet:7.0

WORKDIR /src

# Instalar utilitários adicionais (opcional)
# RUN apt-get update
    # nginx \
    # && apt-get clean -y

CMD ["tail", "-f", "/dev/null"]
