FROM nginx:latest

# Copia a configuração do Nginx
# COPY nginx.conf /etc/nginx/nginx.conf

# Copia os arquivos estáticos para o diretório padrão do Nginx
# COPY ../static /usr/share/nginx/html/static
